apiVersion: batch/v1
kind: CronJob
metadata:
  name: dev-ep-cms-redis-rescheduler-job
  namespace: ep-ops
spec:
  # At hour 2,7,13,19 UTC. (4,10,16,23 GMT-3)
  schedule: "0 2,7,13,19 * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: dev-ep-cms-redis-rescheduler-restart
            app.kubernetes.io/name: dev-ep-cms-redis-rescheduler-restart
        spec:
          restartPolicy: Never

          serviceAccountName: rescheduler-sa

          tolerations:
            - effect: NoSchedule
              key: preemptible
              operator: Equal
              value: "true"

          imagePullSecrets:
            - name: docker-registry

          containers:
            - name: kubectl
              image: bitnami/kubectl:1.15
              command: ["/bin/sh"]
              args:
                - -c
                - |
                  kubectl rollout restart statefulset/cms-revista-digital-redis-master -n ep