---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rescheduler-sa
  namespace: ep-ops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rescheduler-cluster-role
rules:
  - apiGroups: ["apps"]
    resources: ["statefulset", "deployment"]
    verbs: ["get", "patch", "list", "watch", "delete"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rescheduler-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: rescheduler-sa
    namespace: ep-ops
roleRef:
  kind: ClusterRole
  name: rescheduler-cluster-role
  apiGroup: rbac.authorization.k8s.io