---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teste-rescheduler-sa
  namespace: ep-ops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teste-rescheduler-cluster-role
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "patch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teste-rescheduler-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: teste-rescheduler-sa
    namespace: ep-ops
roleRef:
  kind: ClusterRole
  name: teste-rescheduler-cluster-role
  apiGroup: rbac.authorization.k8s.io