# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# application
app:
  servicePort: 5000
  containerPort: 5000

Replicas: 1

# deployment
deployment:
  memoryRequest: null
  cpuRequest: null
  memoryLimit: null
  cpuLimit: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

# container
image:
  repository:
    name: sarahmota
    isPrivate: false
    secretName: null
  name: docker-pushh
  tag: python
  pullPolicy: Always

# ingress
ingress:
  enabled: false
  hostName: null
  sslRedirect: false
  nginxController: false
  certManager:
    enabled: false
    clusterIssuerName: letsecnrypt

# env variables
variables:
  secret:
    POSTGRES_USER: sarah
    POSTGRES_PASSWORD: sarah
  nonSecret:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5000

# horizontal autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  avgCpuUtilization: 20

# startupProbe
startupProbe:
  enabled: false
  httpGet:
    path: "/"
  periodSeconds: 10
  failureThreshold: 20
  timeoutSeconds: 1

# readinessProbe
readinessProbe:
  enabled: false
  httpGet:
    path: "/"
  initialDelaySeconds: 20
  periodSeconds: 30
  failureThreshold: 2
  timeoutSeconds: 3

# livenessProbe
livenessProbe:
  enabled: false
  httpGet:
    path: "/"
  initialDelaySeconds: 20
  periodSeconds: 60
  failureThreshold: 1
  timeoutSeconds: 3
