annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: deployment adjustments
    - kind: added
      description: Documentation detail
    - kind: fixed
      description: Variables in ingress file
  artifacthub.io/containsSecurityUpdates: "true"
apiVersion: v1
description: Helm chart for deployment generic app on Kubernetes
home: https://helm.b3o.io
icon: https://helm.b3o.io/charts/generic-app/icon.png
keywords:
  - generic
  - application
kubeVersion: ">= 1.18.0-0"
maintainers:
  - email: brunogomescorreia@gmail.com
    name: Bruno Correia
name: generic-app
sources:
  - https://github.com/b3outputs/helm-charts
version: v0.1.6
