# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# application
app:
  servicePort: 80
  containerPort: 80

Replicas: 1

# deployment
deployment:
  memoryRequest: null
  cpuRequest: null
  memoryLimit: null
  cpuLimit: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

# container
image:
  repository:
    name: null
    isPrivate: false
    secretName: null
  name: nginx
  tag: latest
  pullPolicy: Always

# ingress
ingress:
  enabled: false
  hostName: null
  sslRedirect: false
  nginxController: false
  certManager:
    enabled: false
    clusterIssuerName: letsecnrypt

# env variables
variables:
  secret: {}
  nonSecret: {}

# horizontal autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  avgCpuUtilization: 50

# startupProbe
startupProbe:
  enabled: false
  httpGet:
    path: "/"
  periodSeconds: 10
  failureThreshold: 20
  timeoutSeconds: 1

# readinessProbe
readinessProbe:
  enabled: false
  httpGet:
    path: "/"
  initialDelaySeconds: 20
  periodSeconds: 30
  failureThreshold: 2
  timeoutSeconds: 3

# livenessProbe
livenessProbe:
  enabled: false
  httpGet:
    path: "/"
  initialDelaySeconds: 20
  periodSeconds: 60
  failureThreshold: 1
  timeoutSeconds: 3
